config/routes.rb
Rails.application.routes.draw do
  # rspec reset_password_instructions
  default_url_options host: 'scm.myattheingiaung@gmail.com'

  # letter opener web
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  get 'home/index'
  devise_for :users, controllers: { invitations: 'users/invitations' }
  resources :posts
  root to: 'posts#index'
  resources :users
  get '/register', to: 'users#new'
  post '/register', to: 'users#create'
  get '/login', to: 'login#login'
  post '/login', to: 'login#actual_login'
  get '/logout', to: 'login#destroy'
  get '/profile/:id', to: 'users#profile'
  post '/posts/import', to: 'posts#import'
  post '/users/import', to: 'users#import'
  get '/posts/copy/:id', to: 'posts#copy_form'
  post '/posts/copy', to: 'posts#copy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_paranoid
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  validates :name, presence: true
  validates :role, presence: true
  validates :phone, allow_blank: true, length: { minimum: 8, maximum: 13 }
  validates :address, length: { maximum: 255 }, allow_blank: true
  validates :birthday, length: { maximum: 255 }, allow_blank: true

  # :database_authenticatable - hashing the password and validating the authenticity of a user while signing in
  # :registerable - user sign_up
  # :recoverable - resetting the user password and send reset instructions
  # :rememberable - manages generating and clearing token for remembering the user from a saved cookie. Rememberable also has utility methods for dealing with serializing the user into the cookie and back from the cookie, trying to lookup the record based on the saved information. You probably wouldn't use rememberable methods directly, they are used mostly internally for handling the remember token
  # :validatable - creates all needed validations for a user email and password. It's optional, given you may want to create the validations by yourself. Automatically validate if the email is present, unique and its format is valid. Also tests presence of password, confirmation and length
  # :confirmable -
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  # Permit the new params here.
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:invite, keys: [:name, :role])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy profile password_change actual_password_change]

  # function: index
  # show user list
  def index
    run User::Operation::Index do |result|
      @users = result[:users]
    end
    respond_to do |format|
      format.html
      format.csv do
        response.headers['Content-Type'] = 'text/csv'
        response.headers['Content-Disposition'] = "attachment; filename=users-#{DateTime.now.strftime("%d%m%Y%H%M")}.csv"
        render template: 'users/index.csv.erb'
      end
    end
  end

  # function: import
  # users import
  def import
    run User::Operation::Import do |result|
      redirect_to root_path, notice: 'User Upload Successfully!'
    end
    if result.failure? && result[:file] || result[:file]
      flash[:file] = result[:file]
      redirect_to users_path
    end
  end

  # function: new
  # show create form
  def new
    run User::Operation::Create::Present
  end

  # function: create
  # create user
  # params user
  def create
    run User::Operation::Create do |_result|
      return redirect_to root_path, notice: 'User Create Successfully!'
    end

    render :new
  end

  # function: edit
  # show edit form
  def edit
    authorize! @user
    run User::Operation::Update::Present
  end

  # function: create
  # update user
  # params user
  def update
    run User::Operation::Update do |_result|
      UserMailer.example(User.new(email: 'scm.myattheingiaung@gmail.com')).deliver
      return redirect_to root_path, notice: 'User Update Successfully!'
    end

    render :edit
  end

  # function: destroy
  # delete user
  def destroy
    run User::Operation::Destroy do |_result|
      return redirect_to root_path, notice: 'User Delete Successfully!'
    end
  end

  # function: profile
  # show details info
  def profile
    run User::Operation::Show do |result|
      @user = result[:model]
      @qr_code = RQRCode::QRCode.new(@user.name)
      @svg = @qr_code.as_svg(
        color: '000',
        shape_rendering: 'crispEdges',
        module_size: 8,
        standalone: true,
        use_path: true
      )
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :password_digest, :phone, :address, :role, :birthday)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/invitations/edit.html.slim
.container style="margin-top:100px;"
  .row
    .col-12.col-md-6.mx-auto
      .card
        .card-body
          h2 = t "devise.invitations.edit.header"

          = simple_form_for(resource, as: resource_name, url: invitation_path(resource_name), html: { method: :put }) do |f|
            = f.error_notification
            = f.hidden_field :invitation_token

            .form-group.mb-4
              = f.label :password, class: 'mb-2'
              = f.password_field :password, class: 'form-control'
              
            .form-group.mb-4
              = f.label :password_confirmation, class: 'mb-2'
              = f.password_field :password_confirmation, class: 'form-control'

            .form-actions
              = f.button :submit, t("devise.invitations.edit.submit_button"), class: 'btn btn-primary'

app/views/users/invitations/new.html.slim
.container style="margin-top:100px;"
  .row
    .col-12.col-md-6.mx-auto
      .card
        .card-body
          h2 = t "devise.invitations.new.header"

          = simple_form_for(resource, as: resource_name, url: invitation_path(resource_name), html: { method: :post }) do |f|
            = f.error_notification

            .form-group.mb-4
              = f.label :email, class: 'mb-2'
              = f.text_field :email, class: 'form-control'
            .form-group.mb-4
              = f.label :name, class: 'mb-2'
              = f.text_field :name, class: 'form-control'
            .form-group.mb-4
              = f.label :create_as, class: 'mb-2'
              .form-check.d-flex.p-0.mb-2
                = f.radio_button :role, 'admin'
                = f.label :admin
              .form-check.d-flex.p-0
                = f.radio_button :role, 'user'
                = f.label :user

            .form-actions
              = f.button :submit, t("devise.invitations.new.submit_button"), class: 'btn btn-primary'